---
name: 'Video-Shooting '
about: 'product to be video-shoot '
title: Video Shooting
labels: ''
assignees: ''
body:
-type: textarea
 attributes:
  label: **What is the product name**
  description: please provide the full name of the product
  validation: 
  required: false
  -type: textarea
 attributes:
  label: ****What is the video shooting all about****
  description: please provide information
  validation: 
  required: false

---

